from __future__ import annotations

from typing import AsyncGenerator, Iterable, Protocol

from job_runner.models import JobPaths, JobRecord, JobSpec, JobStatus


class JobStoreProtocol(Protocol):
    async def create(self, job_id: str, spec: JobSpec, paths: JobPaths) -> JobRecord: ...
    async def get(self, job_id: str) -> JobRecord: ...
    async def mark_running(self, job_id: str) -> JobRecord: ...
    async def mark_finished(
        self,
        job_id: str,
        status: JobStatus,
        exit_code: int | None,
        error: str | None = None,
        artifacts: Iterable[str] | None = None,
    ) -> JobRecord: ...
    async def update_artifacts(
        self, job_id: str, artifacts: Iterable[str]
    ) -> JobRecord: ...


class LogStoreProtocol(Protocol):
    async def register(self, job_id: str) -> None: ...
    async def append(self, job_id: str, text: str) -> None: ...
    async def mark_complete(self, job_id: str) -> None: ...
    async def tail(self, job_id: str) -> list[str]: ...
    def stream(
        self, job_id: str, start_at: int = 0
    ) -> AsyncGenerator[str, None]: ...
